#Bergur ingi Ólafsson, Ísar Daði Pálsson
#Lokaverkefni
#24.04.2017


Sokki = {"nafn" : "Sokki" , "Þyngd" : 41 , "Mjólkurlagni dætra" : 108 , "Einkunn ullar" : 7.0 , "Fjöldi afkvæma" : 0 , "Einkunn læris" : 17.3 , "Frjósemi" : 108 , "Gerð/þykkt bakvöðva" : 144 , "Einkunn fyrir malir" : 8.5}
Freydir = {"nafn" : "Freyðir" , "Þyngd" : 46.4 , "Mjólkurlagni dætra" : 105 , "Einkunn ullar" : 7.9 , "Fjöldi afkvæma" : 135 , "Einkunn læris" : 17.4 , "Frjósemi" : 103 , "Gerð/þykkt bakvöðva" : 118 , "Einkunn fyrir malir" : 8.6}
Vodvi = {"nafn" : "Vöðvi" , "Þyngd" : 47 , "Mjólkurlagni dætra" : 100 , "Einkunn ullar" : 8.0 , "Fjöldi afkvæma" : 0 , "Einkunn læris" : 17.5 , "Frjósemi" : 106 , "Gerð/þykkt bakvöðva" : 112 , "Einkunn fyrir malir" : 9.0}
Kjoi = {"nafn" : "Kjói" , "Þyngd" : 48.8 , "Mjólkurlagni dætra" : 116 , "Einkunn ullar" : 8.4 , "Fjöldi afkvæma" : 160 , "Einkunn læris" : 17.0 , "Frjósemi" : 94 , "Gerð/þykkt bakvöðva" : 111 , "Einkunn fyrir malir" : 8.3}
Bogi = {"nafn" : "Bogi" , "Þyngd" : 49.9 , "Mjólkurlagni dætra" : 110 , "Einkunn ullar" : 8.3 , "Fjöldi afkvæma" : 310 , "Einkunn læris" : 17.3 , "Frjósemi" : 102 , "Gerð/þykkt bakvöðva" : 116 , "Einkunn fyrir malir" : 8.5}
Falur = {"nafn" : "Falur" , "Þyngd" : 48.3 , "Mjólkurlagni dætra" : 106 , "Einkunn ullar" : 8.2 , "Fjöldi afkvæma" : 26 , "Einkunn læris" : 16.9 , "Frjósemi" : 95 , "Gerð/þykkt bakvöðva" : 114 , "Einkunn fyrir malir" : 8.3}
Bordi = {"nafn" : "Borði" , "Þyngd" : 42 , "Mjólkurlagni dætra" : 110 , "Einkunn ullar" : 8.0 , "Fjöldi afkvæma" : 0 , "Einkunn læris" : 18.0 , "Frjósemi" : 104 , "Gerð/þykkt bakvöðva" : 0 , "Einkunn fyrir malir" : 9.0}
Bramli = {"nafn" : "Bramli" , "Þyngd" : 47.5 , "Mjólkurlagni dætra" : 104 , "Einkunn ullar" : 7.8 , "Fjöldi afkvæma" : 347 , "Einkunn læris" : 17.2 , "Frjósemi" : 106 , "Gerð/þykkt bakvöðva" : 102 , "Einkunn fyrir malir" : 8.4}
Kaldi = {"nafn" : "Kaldi" , "Þyngd" : 47.8 , "Mjólkurlagni dætra" : 100 , "Einkunn ullar" : 7.9 , "Fjöldi afkvæma" : 218 , "Einkunn læris" : 17.1 , "Frjósemi" : 135 , "Gerð/þykkt bakvöðva" : 93 , "Einkunn fyrir malir" : 8.4}
Vorm = {"nafn" : "Vorm" , "Þyngd" : 47.6 , "Mjólkurlagni dætra" : 95 , "Einkunn ullar" : 7.8 , "Fjöldi afkvæma" : 158 , "Einkunn læris" : 17.3 , "Frjósemi" : 111 , "Gerð/þykkt bakvöðva" : 122 , "Einkunn fyrir malir" : 8.5}
Smyrill = {"nafn" : "smyrill" , "Þyngd" : 47.8 , "Mjólkurlagni dætra" : 101 , "Einkunn ullar" : 7.9 , "Fjöldi afkvæma" : 97 , "Einkunn læris" : 17.2 , "Frjósemi" : 95 , "Gerð/þykkt bakvöðva" : 114 , "Einkunn fyrir malir" : 8.4}
Prjonn = {"nafn" : "Prjónn" , "Þyngd" : 47.5 , "Mjólkurlagni dætra" : 110 , "Einkunn ullar" : 7.8 , "Fjöldi afkvæma" : 370 , "Einkunn læris" : 17.5 , "Frjósemi" : 105 , "Gerð/þykkt bakvöðva" : 122 , "Einkunn fyrir malir" : 8.6}
Grabotn = {"nafn" : "Grábotn" , "Þyngd" : 45 , "Mjólkurlagni dætra" : 102 , "Einkunn ullar" : 7.5 , "Fjöldi afkvæma" : 0 , "Einkunn læris" : 17.5 , "Frjósemi" : 106 , "Gerð/þykkt bakvöðva" : 139 , "Einkunn fyrir malir" : 8.5}
Kongur = {"nafn" : "Kóngur" , "Þyngd" : 59 , "Mjólkurlagni dætra" : 108 , "Einkunn ullar" : 8.0 , "Fjöldi afkvæma" : 0 , "Einkunn læris" : 17.5 , "Frjósemi" : 105 , "Gerð/þykkt bakvöðva" : 114 , "Einkunn fyrir malir" : 8.5}
Garpur = {"nafn" : "Garpur" , "Þyngd" : 48.6 , "Mjólkurlagni dætra" : 106 , "Einkunn ullar" : 8.2 , "Fjöldi afkvæma" : 101 , "Einkunn læris" : 17.3 , "Frjósemi" : 98 , "Gerð/þykkt bakvöðva" : 116 , "Einkunn fyrir malir" : 8.5}
Broddi = {"nafn" : "Broddi" , "Þyngd" : 57 , "Mjólkurlagni dætra" : 92 , "Einkunn ullar" : 7.5 , "Fjöldi afkvæma" : 0 , "Einkunn læris" : 18.0 , "Frjósemi" : 99 , "Gerð/þykkt bakvöðva" : 144 , "Einkunn fyrir malir" : 9.5}
Frakkson = {"nafn" : "Frakkson" , "Þyngd" : 49.6 , "Mjólkurlagni dætra" : 110 , "Einkunn ullar" : 8.4 , "Fjöldi afkvæma" : 325 , "Einkunn læris" : 17.2 , "Frjósemi" : 106 , "Gerð/þykkt bakvöðva" : 117 , "Einkunn fyrir malir" : 8.4}
Raftur = { "nafn" : "Raftur" , "Þyngd í kílóum" : 47.1 , "Mjólkurlagni dætra" : 106, "Einkunn ullar" : 7.8 , "Fjöldi afkvæmalir" : 1406, "Einkunn læris" : 17.6 , "Frjósemi" : 112, "Gerð/þykkt bakvöðva" : 122, "Einkunn fyrir malir" : 8.6,}
Blossi = { "nafn" : "Blossi" , "Þyngd í kílóum" : 54 , "Mjólkurlagni dætra" : 108, "Einkunn ullar" : 8.5 , "Fjöldi afkvæmalir" : 0, "Einkunn læris" : 18.0 , "Frjósemi" : 111, "Gerð/þykkt bakvöðva" : 113, "Einkunn fyrir malir" : 9.0,}
Blettur = { "nafn" : "Blettur" , "Þyngd í kílóum" : 44.9 , "Mjólkurlagni dætra" : 100, "Einkunn ullar" : 7.9 , "Fjöldi afkvæmalir" : 332, "Einkunn læris" : 17.2 , "Frjósemi" : 99, "Gerð/þykkt bakvöðva" : 109, "Einkunn fyrir malir" : 8.3,}
Mundi = { "nafn" : "Mundi" , "Þyngd í kílóum" : 46 , "Mjólkurlagni dætra" : 104, "Einkunn ullar" : 7.5 , "Fjöldi afkvæmalir" : 0, "Einkunn læris" : 16.5 , "Frjósemi" : 110, "Gerð/þykkt bakvöðva" : 126, "Einkunn fyrir malir" : 8.5,}
Hriflon = { "nafn" : "Hriflon" , "Þyngd í kílóum" : 49 , "Mjólkurlagni dætra" : 112, "Einkunn ullar" : 8.0 , "Fjöldi afkvæmalir" : 0, "Einkunn læris" : 18.0 , "Frjósemi" : 110, "Gerð/þykkt bakvöðva" : 124, "Einkunn fyrir malir" : 8.5,}
Skrauti = { "nafn" : "Skrauti" , "Þyngd í kílóum" : 45 , "Mjólkurlagni dætra" : 111, "Einkunn ullar" : 7.0 , "Fjöldi afkvæmalir" : 0, "Einkunn læris" : 17.3 , "Frjósemi" : 98, "Gerð/þykkt bakvöðva" : 112, "Einkunn fyrir malir" : 8.5,}
Undri = { "nafn" : "Undri" , "Þyngd í kílóum" : 49.1 , "Mjólkurlagni dætra" : 108, "Einkunn ullar" : 8.4 , "Fjöldi afkvæmalir" : 76, "Einkunn læris" : 17.2, "Frjósemi" : 100, "Gerð/þykkt bakvöðva" : 109, "Einkunn fyrir malir" : 8.4,}
As = { "nafn" : "Ás" , "Þyngd í kílóum" : 48.8 , "Mjólkurlagni dætra" : 121, "Einkunn ullar" : 8.1 , "Fjöldi afkvæmalir" : 82, "Einkunn læris" : 17.2 , "Frjósemi" : 108, "Gerð/þykkt bakvöðva" : 110, "Einkunn fyrir malir" : 8.3,}
Gotti = {"nafn" : "Gotti" , "Þyngd" : 47.2 , "Mjólkurlagni dætra" : 100 , "Einkunn ullar" : 8.0 , "Fjöldi afkvæma" : 182 , "Einkunn læris" : 17.5 , "Frjósemi" : 102 , "Gerð/þykkt bakvöðva" : 119 , "Einkunn fyrir malir" : 8.6}
Hroi = {"nafn" : "Hrói" , "Þyngd" : 63 , "Mjólkurlagni dætra" : 107 , "Einkunn ullar" : 8.0 , "Fjöldi afkvæma" : 0 , "Einkunn læris" : 17.3 , "Frjósemi" : 108 , "Gerð/þykkt bakvöðva" : 108 , "Einkunn fyrir malir" : 8.5}
Dokkvi = {"nafn" : "Dökkvi" , "Þyngd" : 45.5 , "Mjólkurlagni dætra" : 102 , "Einkunn ullar" : 7.8 , "Fjöldi afkvæma" : 157 , "Einkunn læris" : 17.2 , "Frjósemi" : 105 , "Gerð/þykkt bakvöðva" : 120 , "Einkunn fyrir malir" : 8.5}
Bolli = {"nafn" : "Bolli" , "Þyngd" : 51 , "Mjólkurlagni dætra" : 109 , "Einkunn ullar" : 9.0 , "Fjöldi afkvæma" : 0 , "Einkunn læris" : 17.5 , "Frjósemi" : 111 , "Gerð/þykkt bakvöðva" : 109 , "Einkunn fyrir malir" : 9.0}
Tyr = {"nafn" : "Týr" , "Þyngd" : 38 , "Mjólkurlagni dætra" : 96 , "Einkunn ullar" : 8.0 , "Fjöldi afkvæma" : 0 , "Einkunn læris" : 17.5 , "Frjósemi" : 105 , "Gerð/þykkt bakvöðva" : 131 , "Einkunn fyrir malir" : 8.5}
Papi = {"nafn" : "Papi" , "Þyngd" : 45.6 , "Mjólkurlagni dætra" : 82 , "Einkunn ullar" : 8.0 , "Fjöldi afkvæma" : 428 , "Einkunn læris" : 17.6 , "Frjósemi" : 106 , "Gerð/þykkt bakvöðva" : 140 , "Einkunn fyrir malir" : 8.7}
Tengill = { "nafn" : "Tengill" , "Þyngd í kílóum" : 45 , "Mjólkurlagni dætra" : 94 , "Einkunn ullar" :8 , "Fjöldi afkvæma" : 0, "Einkunn læris" : 17.5 , "Frjósemi" : 97, "Gerð/þykkt bakvöðva" : 145, "Einkunn fyrir malir" : 9,}
At = { "nafn" : "At" , "Þyngd í kílóum" :  45.6 , "Mjólkurlagni dætra" : 110 , "Einkunn ullar" : 7.9 , "Fjöldi afkvæma" : 244, "Einkunn læris" : 17.5 , "Frjósemi" : 110, "Gerð/þykkt bakvöðva" : 139, "Einkunn fyrir malir" : 8.5,}
Grani = { "nafn" : "Gráni" , "Þyngd í kílóum" :  48.3 , "Mjólkurlagni dætra" : 111 , "Einkunn ullar" : 7.9 , "Fjöldi afkvæma" : 381, "Einkunn læris" : 17.4 , "Frjósemi" : 105, "Gerð/þykkt bakvöðva" : 122, "Einkunn fyrir malir" : 8.6,}
Ylur = { "nafn" : "Ylur" , "Þyngd í kílóum" : 47.4 , "Mjólkurlagni dætra" : 111 , "Einkunn ullar" : 8 , "Fjöldi afkvæma" : 184, "Einkunn læris" : 17.2 , "Frjósemi" : 96, "Gerð/þykkt bakvöðva" : 117, "Einkunn fyrir malir" : 8.4,}
Neisti = { "nafn" : "Neisti" , "Þyngd í kílóum" :  47 , "Mjólkurlagni dætra" : 106 , "Einkunn ullar" : 8.5 , "Fjöldi afkvæma" : 0, "Einkunn læris" : 18.5 , "Frjósemi" : 104, "Gerð/þykkt bakvöðva" : 116, "Einkunn fyrir malir" : 9,}
Logi = { "nafn" : "Logi" , "Þyngd í kílóum" :  53 , "Mjólkurlagni dætra" : 109 , "Einkunn ullar" : 8.5 , "Fjöldi afkvæma" : 0, "Einkunn læris" : 18 , "Frjósemi" : 101, "Gerð/þykkt bakvöðva" : 114, "Einkunn fyrir malir" : 9,}
Kveikur = { "nafn" : "Kveikur" , "Þyngd í kílóum" :  49 , "Mjólkurlagni dætra" : 113 , "Einkunn ullar" : 7.8 , "Fjöldi afkvæma" : 1085, "Einkunn læris" : 17.4 , "Frjósemi" : 106, "Gerð/þykkt bakvöðva" : 118, "Einkunn fyrir malir" : 8.6,}
Shrek = { "nafn" : "Shrek" , "Þyngd í kílóum" : 49.5 , "Mjólkurlagni dætra" : 117, "Einkunn ullar" : 8.1 , "Fjöldi afkvæmalir" : 82, "Einkunn læris" : 17.3 , "Frjósemi" : 103, "Gerð/þykkt bakvöðva" : 118, "Einkunn fyrir malir" : 8.5,}
Cat = { "nafn" : "Cat" , "Þyngd í kílóum" : 47.7 , "Mjólkurlagni dætra" : 98, "Einkunn ullar" : 7.6 , "Fjöldi afkvæmalir" : 193, "Einkunn læris" : 17.5 , "Frjósemi" : 100, "Gerð/þykkt bakvöðva" : 128, "Einkunn fyrir malir" : 8.6,}
Fannar = { "nafn" : "Fannar" , "Þyngd í kílóum" : 46.4 , "Mjólkurlagni dætra" : 105, "Einkunn ullar" : 7.9 , "Fjöldi afkvæmalir" : 222, "Einkunn læris" : 17.4 , "Frjósemi" : 101, "Gerð/þykkt bakvöðva" : 125, "Einkunn fyrir malir" : 8.6,}
Hvellur = { "nafn" : "Hvellur" , "Þyngd í kílóum" : 48.8 , "Mjólkurlagni dætra" : 112, "Einkunn ullar" : 8.0 , "Fjöldi afkvæmalir" : 552, "Einkunn læris" : 17.3 , "Frjósemi" : 96, "Gerð/þykkt bakvöðva" : 113, "Einkunn fyrir malir" : 8.6,}
Þrottur = {"nafn" : "Þróttur" , "Þyngd" : 48.0 , "Mjólkurlagni dætra" : 106 , "Einkunn ullar" : 7.8 , "Fjöldi afkvæma" : 222 , "Einkunn læris" : 17.4 , "Frjósemi" : 105 , "Gerð/þykkt bakvöðva" : 121 , "Einkunn fyrir malir" : 8.5}
Bifur = {"nafn" : "Bifur" , "Þyngd" : 45.5 , "Mjólkurlagni dætra" : 96 , "Einkunn ullar" : 7.7 , "Fjöldi afkvæma" : 407 , "Einkunn læris" : 17.5 , "Frjósemi" : 110 , "Gerð/þykkt bakvöðva" : 115 , "Einkunn fyrir malir" : 8.7}
Stali = {"nafn" : "Stáli" , "Þyngd" : 85 , "Mjólkurlagni dætra" : 102 , "Einkunn ullar" : 8.0 , "Fjöldi afkvæma" : 0 , "Einkunn læris" : 17.5 , "Frjósemi" : 100 , "Gerð/þykkt bakvöðva" : 130 , "Einkunn fyrir malir" : 9.0}
Falki = {"nafn" : "Fálki" , "Þyngd" : 51 , "Mjólkurlagni dætra" : 103 , "Einkunn ullar" : 7.5 , "Fjöldi afkvæma" : 0 , "Einkunn læris" : 17.5 , "Frjósemi" : 102 , "Gerð/þykkt bakvöðva" : 142 , "Einkunn fyrir malir" : 9.0}
Kjarkur = {"nafn" : "Kjarkur" , "Þyngd" : 48 , "Mjólkurlagni dætra" : 108 , "Einkunn ullar" : 7.5 , "Fjöldi afkvæma" : 0 , "Einkunn læris" : 17.0 , "Frjósemi" : 108 , "Gerð/þykkt bakvöðva" : 0 , "Einkunn fyrir malir" : 8.5}
Holmi = {"nafn" : "Hólmi" , "Þyngd" :  45 , "Mjólkurlagni dætra" : 104 , "Einkunn ullar" : 7.5 , "Fjöldi afkvæma" : 0 , "Einkunn læris" : 18.0 , "Frjósemi" : 95 , "Gerð/þykkt bakvöðva" : 0 , "Einkunn fyrir malir" : 9.0}
Puki = {"nafn" : "Púki" , "Þyngd" : 49.0 , "Mjólkurlagni dætra" : 111 , "Einkunn ullar" : 7.7 , "Fjöldi afkvæma" : 403 , "Einkunn læris" : 17.3 , "Frjósemi" : 114 , "Gerð/þykkt bakvöðva" : 119 , "Einkunn fyrir malir" : 8.5}
Mjoðir = {"nafn" : "Mjóðir" , "Þyngd" : 46.4 , "Mjólkurlagni dætra" : 102 , "Einkunn ullar" : 8.0 , "Fjöldi afkvæma" : 210 , "Einkunn læris" : 17.5 , "Frjósemi" : 103 , "Gerð/þykkt bakvöðva" : 127 , "Einkunn fyrir malir" : 8.6}
Mokollur = {"nafn" : "Mókollur" , "Þyngd" : 49.6 , "Mjólkurlagni dætra" : 111 , "Einkunn ullar" : 7.9 , "Fjöldi afkvæma" : 135 , "Einkunn læris" : 16.9 , "Frjósemi" : 122 , "Gerð/þykkt bakvöðva" : 102 , "Einkunn fyrir malir" : 8.2}
